# Generated by Django 4.1.7 on 2023-04-16 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='wine_shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=50)),
                ('brand_dis', models.CharField(max_length=50)),
                ('brand_rate', models.IntegerField()),
                ('brand_type', models.CharField(max_length=20)),
            ],
        ),
    ]
